<?php
declare(strict_types=1); require_once __DIR__.'/auth.php'; require_admin(); $pageTitle='Users'; $file=(string)(cfg()['users_file']??'/etc/wyze-dashboard/users.json'); $message=''; $error='';
function save_users_file(string $file,array $users):void { $admins=0; foreach($users as $u) if(!empty($u['enabled'])&&(($u['role']??'')==='admin')) $admins++; if($admins!==1) throw new RuntimeException('There must be exactly one enabled admin account.'); $tmp=$file.'.tmp'; if(file_put_contents($tmp,json_encode(['users'=>array_values($users)],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n",LOCK_EX)===false) throw new RuntimeException('Could not write users file.'); chmod($tmp,0640); if(!rename($tmp,$file)){@unlink($tmp);throw new RuntimeException('Could not replace users file.');}}
$users=load_users();
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){verify_csrf();$action=(string)($_POST['action']??'');try{
 if($action==='add'){ $name=trim((string)($_POST['username']??''));$pw=(string)($_POST['password']??''); if(!preg_match('/^[A-Za-z0-9_.-]{3,32}$/',$name)) throw new RuntimeException('Username must be 3-32 safe characters.'); if(strlen($pw)<12) throw new RuntimeException('Password must be at least 12 characters.'); foreach($users as $u) if(($u['username']??'')===$name) throw new RuntimeException('Username already exists.'); $users[]=['username'=>$name,'password_hash'=>password_hash($pw,PASSWORD_DEFAULT),'role'=>'viewer','enabled'=>true]; save_users_file($file,$users); $message="Added {$name}."; }
 if($action==='password'){ $name=(string)($_POST['username']??'');$pw=(string)($_POST['password']??''); if(strlen($pw)<12) throw new RuntimeException('Password must be at least 12 characters.');$found=false;foreach($users as &$u){if(($u['username']??'')===$name){$u['password_hash']=password_hash($pw,PASSWORD_DEFAULT);$found=true;break;}}unset($u);if(!$found)throw new RuntimeException('User not found.');save_users_file($file,$users);$message="Password updated for {$name}."; }
 if($action==='toggle'){ $name=(string)($_POST['username']??''); foreach($users as &$u){if(($u['username']??'')===$name){if(($u['role']??'')==='admin')throw new RuntimeException('Admin cannot be disabled.');$u['enabled']=empty($u['enabled']);break;}}unset($u);save_users_file($file,$users);$message="Updated {$name}."; }
 if($action==='delete'){ $name=(string)($_POST['username']??'');$new=[];foreach($users as $u){if(($u['username']??'')===$name){if(($u['role']??'')==='admin')throw new RuntimeException('Admin cannot be deleted.');continue;}$new[]=$u;}$users=$new;save_users_file($file,$users);$message="Deleted {$name}."; }
 $users=load_users(); }catch(Throwable $e){$error=$e->getMessage();}}
require __DIR__.'/header.php';?>
<div class="page-head"><div><h1>Users</h1><p class="muted">One admin; additional accounts are read-only viewers.</p></div></div><?php if($message):?><div class="alert success"><?=h($message)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=h($error)?></div><?php endif;?>
<section class="panel"><h2>Add viewer</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add"><label>Username<input name="username" required pattern="[A-Za-z0-9_.-]{3,32}"></label><label>Password<input type="password" name="password" required minlength="12"></label><div style="align-self:end"><button>Add viewer</button></div></form></section>
<section class="panel"><h2>Accounts</h2><div class="table-wrap"><table><thead><tr><th>Username</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=h((string)$u['username'])?></td><td><?=h((string)($u['role']??'viewer'))?></td><td><?=!empty($u['enabled'])?'Enabled':'Disabled'?></td><td><div class="user-actions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="password"><input type="hidden" name="username" value="<?=h((string)$u['username'])?>"><input type="password" name="password" minlength="12" placeholder="New password" required><button class="secondary">Change password</button></form><?php if(($u['role']??'')!=='admin'):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="username" value="<?=h((string)$u['username'])?>"><button class="secondary"><?=!empty($u['enabled'])?'Disable':'Enable'?></button></form><form method="post" onsubmit="return confirm('Delete this user?');"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="username" value="<?=h((string)$u['username'])?>"><button class="danger">Delete</button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></section><?php require __DIR__.'/footer.php';?>
